### ISSUE TITLE
Form submission enhancements

### ISSUE THREAD

**Issue by seancdavis** [ample/gatsby-starter-ample#206]
This is to consolidate all the form enhancements around the submission process. Here are the tasks:

- [x] Build a serverless function to act as an engine. We can plug in drivers that forward the data to one or more services, such as Hubspot, Pardot, Netlify. Let's put the base in first with a Netlify driver. We'll add the other drivers as the needs arise in various projects.
- [ ] Submit forms asynchronously, showing success and error messages as appropriate. #80
- [ ] Put form button in loading state while the request is being submitted. #100 
- [ ] Form button should be disabled when there are invalid fields. #98
- [ ] Add error messages to invalid fields on submit. #95 
- [ ] Explicitly define the schema for forms. #180

**Comment by seancdavis** [comment]
😢 

😉
